use_frameworks!

platform :ios, '9.0'

target 'WSSPageViewController_Example' do
  pod 'WSSPageViewController', :path => '../'

  target 'WSSPageViewController_Tests' do
    inherit! :search_paths

    
  end
end
